#!/usr/bin/env bash

export CONTECO_LABEL="metricbeat.node - ConteEco"
export CONTECO_DESCRIPTION="The ElasticSearch Metricbeat base image configured for system and docker monitoring."

export CONTECO_TYPE="metricbeat"
export CONTECO_NAME="node"
export CONTECO_TAG="7.9.2"

export CONTECO_BASE="metricbeat.base"
export CONTECO_BUILD="image"
